spring:
  application:
    name:
      talent-arena
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://ep-tiny-wave-a9n1gz6q-pooler.gwc.azure.neon.tech/talentarena?user=talentarena_owner&password=npg_jZuCkF0N6gfG&sslmode=require

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: talentarena
talent-arena:
  client:
    apiKey: ${RAPID_API_TOKEN}
    location-verifier:
      baseUrl: ${LOCATION_VERIFIER_BASEURL}
      host: ${LOCATION_VERIFIER_HOST}
    sim-swap:
      host: ${RAPID_API_HOST}
      baseUrl: ${RAPID_API_URL}
  jwt:
    secret: 5468566D597133743677397A24432646294A404E635266556A586E5A72347537